# example netlify.toml
[build]
  command = "npm install && npx elm make src/Main.elm --output dist/index.html"
  functions = "functions"
  publish = "dist"

[dev]
  command = "npx elm-live src/Main.elm"
  targetPort = 8000
  publish = "dist"
  autoLaunch = true
  framework = "#custom"
