# example netlify.toml
[build]
  base = "site/"
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public"

[dev]
  command = "npx elm-live src/Main.elm --dir=./public -- --output=public/elm.js"
  targetPort = 8000
  publish = "public"
  autoLaunch = true
  framework = "#custom"
